application: borris123psnbeta
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|swf|js|css))$
  static_files: \1
  upload: .+\.(gif|png|jpg|swf|js|css)$
  application_readable: true

# Serve index.
- url: /
  script: index.php

# Serve php scripts.
- url: /(.+\.php)$
  script: \1